server:
  port: 8000
  error:
    # Не включаем stacktrace в http ответ ошибки
    include-stacktrace: never

logging:
  level:
    # Уровень логирования
    ru.greenpix.messenger: ${LOGGING_LEVEL:info}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:10000}/${DB_NAME:lecture-hall}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    baseline-on-migrate: true
  security:
    oauth2:
      client:
        registration:
          vk:
            provider: vk
            client-name: VK
            client-id: 51679482
            client-secret: 4IlKzeDOBPRy80wrMNgj
            scope:
              - video
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
        provider:
          vk:
            authorization-uri: https://oauth.vk.com/authorize
            token-uri: https://oauth.vk.com/access_token
            user-info-uri: https://api.vk.com/method/users.get?v=5.131
            user-name-attribute: first_name

springdoc:
  swagger-ui:
    path: /swagger