spring:

vk:
  access-token: "vk1.a._TpqPv2oYLljew_Ww64DSfvmJ1Jjsf0VKv3uoAjDMqslR0JJmcj_WHeTwziLG9vfIjnYthZovarqKW1kmi6RVPhkc7dhe6dCdM-3astKP3nsCMsTWySziRUu8M65p6b2qySR20w6_8OAFFZlMEtsTyrNedHJujWTtfbrI6LC8P5yYOQ1ImzviXGZu2jROkNwqoSDIEQ1asNMMFC0-v0tng"
