server:
  port: 8001
  error:
    # Не включаем stacktrace в http ответ ошибки
    include-stacktrace: never

logging:
  level:
    # Уровень логирования
    ru.greenpix.messenger: ${LOGGING_LEVEL:info}

spring:
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:1GB}
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:10001}/${DB_NAME:video}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    baseline-on-migrate: true
  rabbitmq:
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:/}
    host: ${RABBITMQ_HOST:127.0.0.1}
    port: ${RABBITMQ_PORT:5672}

amqp:
  topic:
    video: ${RABBITMQ_TOPIC:video-topic}